### ISSUE TITLE
readme typo

### ISSUE THREAD

**Issue by wsbky** [matsui54/denite-nvim-lsp#1]
| in README(maybe typo)  | correct source name |
|--|--|
|[`lsp/diagnostics_all`](https://github.com/matsui54/denite-nvim-lsp#lspdiagnostics_all)|`lsp/diagnostic_all`|
|[`lsp/diagnostics_buffer`](https://github.com/matsui54/denite-nvim-lsp#lspdiagnostics_buffer)|`lsp/diagnostic_buffer`|

Thank you for an excellent plugin ^^

**Comment by matsui54** [comment]
Thank you!
